---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install apache httpd 
  ansible.builtin.apt:
    name: apache2
    state: present

- name: Ensure apache is running and enabled
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: yes

- name: Adjust firewall for Apache
  community.general.ufw:
    rule: allow
    name: 'Apache'

- name: Ensure /var/www/html exists
  ansible.builtin.file:
    path: "{{index_path}}"
    state: directory

- name: Deploy custom index.html
  ansible.builtin.template:
    src: "{{index_template_path}}"
    dest: "{{custom_index_path}}"
    
